export const ENDPOINT = {
    MAIN_HOST: 'https://worker.bnoop.net/api/',
    AUTH: {
        // LOGIN: 'Tenant/TenantManagement/LogIn',
        LOGIN: 'Auth/LogInDashBoard',
        FORGOT: 'User/ForgetPassword',
        CHECK_OTP: 'User/CheckOTPCode',
        RESET: 'User/ResetPassword',
    },
    COMPANY: 'Company',
    NATIONALITY: 'Nationality',
    CITY: 'City',
    REGION: 'Region',
    JOB: 'Job',
    SERVICES: 'TypeOfService',
    PROVIDED_SERVICES: 'Provided_Services',
    BRANCHES: 'Branch',
    COMPANY_BRANCHES: 'CompanyBranch',
    SHIFTS: 'Shift',
    WORKER: "Worker",
    USER_PERMISSION: 'AppPermission',
    SERVICES_SYSTEMS: 'SystemOfService',
    SERVICES_PRICING: 'ServicePriceHead',
    SERVICES_DURATION: 'ListDurationOfServices',
    ORDERS: 'Order',
    ORDER_REPORT: 'OrderReport',
    OFFERS: "Offers",
    USER: "User",
    ROLES: "Role",
    ADVERTISEMENT: "Advertisement",
    DASHBOARD: "Dashboard",
    LIST_ORDER_STATUS: "ListOrderStatus",
    TOTAL_COMMISSIONS: "Order",
    DETAILED_COMMISSIONS: "Order",
    COMMISSION_REPORT: "OrderReport"

}
